version: "3.9"
services:
    server:
      build:
        context: .
        dockerfile: Dockerfile
      image: 940234352785.dkr.ecr.us-west-2.amazonaws.com/groceryregistry/server
      env_file:
        - .env
      ports:
        - "3000:3000"

    grocerywebsite:
      build:
        context: grocerywebsite
        dockerfile: Dockerfile
      image: 940234352785.dkr.ecr.us-west-2.amazonaws.com/groceryregistry/grocerywebsite
      ports:
        - "80:80"

    cronjob:
      build:
        context: .
        dockerfile: ./cronjob/Dockerfile
      image: 940234352785.dkr.ecr.us-west-2.amazonaws.com/groceryregistry/cronjob
      env_file:
        - .env
